name: Vanessa Powers
favicon: null
layout_spectrum: 0.010506036691367626
typography_spectrum: 0.5526587490458041
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.42809607717208564
  lightness: 0.5304899003822356
  saturation: 0.7994804629124701
  rhythmicContrast: 0.5719093293882906
purpose: []
